apiVersion: eksctl.io/v1alpha5 
kind: ClusterConfig 

metadata: 
  name: ml-bookcamp-eks 
  region: us-east-2 
  version: "1.18" 

nodeGroups: 
  - name: ng 
    desiredCapacity: 2 
    instanceType: m5.xlarge 