services:
  zookeeper:
    image: quay.io/debezium/zookeeper:2.6
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - debezium-network
  kafka:
    image: quay.io/debezium/kafka:2.6
    ports:
      - 9092:9092
    networks:
      - debezium-network
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    image: quay.io/debezium/example-mysql:2.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    networks:
      - debezium-network
  connect:
    image: quay.io/debezium/connect:2.6
    ports:
      - 8083:8083
    networks:
      - debezium-network
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  python:
    image: python:3.12
    networks:
      - debezium-network
    depends_on:
      - kafka
      - mysql
      - connect
    stdin_open: true
    tty: true
networks:
  debezium-network:
    driver: bridge